tasks_file_path: "data/preprocessed/mysql_test/dev/tasks.pkl"
subset_file_path: null
db_root_dir: "mysql_db"
n_processes: 1
max_rollout_steps: 2
max_depth: 2
exploration_constant: 1.414
save_root_dir: "results/mysql_exp"
mcts_model_kwargs:
    model: "claude-haiku-4-5-20251001"
    n: 1
    top_p: 0.8
    max_tokens: 65536
    temperature: 0.8
    n_strategy: "single"
reward_model_kwargs: null
